# AI-Hub Repository Validation Workflow
# Validates repository structure and markdown files

name: AI-Hub Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate Repository Structure
      run: |
        echo "✅ Validating AI-Hub repository structure..."

        # Check core directories exist
        test -d "docs" || (echo "❌ Missing docs directory" && exit 1)
        test -d "scripts" || (echo "❌ Missing scripts directory" && exit 1)
        test -d "shared" || (echo "❌ Missing shared directory" && exit 1)

        # Check critical files exist
        test -f "README.md" || (echo "❌ Missing README.md" && exit 1)
        test -f "shared/commands-to-run.md" || (echo "❌ Missing commands-to-run.md" && exit 1)

        echo "✅ Repository structure validation passed!"

    - name: Validate Scripts
      run: |
        echo "✅ Validating executable scripts..."

        # Check script permissions
        for script in scripts/*.sh; do
          if [ -f "$script" ]; then
            test -x "$script" || (echo "❌ Script $script is not executable" && exit 1)
            echo "✅ $script is executable"
          fi
        done

        echo "✅ Script validation passed!"

    - name: Check Markdown Files
      run: |
        echo "✅ Checking markdown files for basic syntax..."

        # Basic markdown validation
        find . -name "*.md" -exec echo "Checking {}" \;

        echo "✅ Markdown validation completed!"
